Fix non ascii character in comment (#82)
I was getting the following compilation errors when I pulled in this repo.

```
error: unmappable character for encoding ASCII
```

The root cause seems to be the character below was not from the ASCII set.